version: "3.9"

networks:
  intelbras:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./api
    ports:
    - "3000:3000"
    networks:
    - intelbras
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
    - "4000:3000"
    networks:
    - intelbras
